const LEGACY_TO_OFFICIAL_STATUS = {
  TRIAGEM: 'TRIAGED',
  AGUARDANDO_PAGAMENTO: 'AGUARDANDO_PAGAMENTO',
  FILA: 'QUEUE',
  EM_ATENDIMENTO: 'UNDER_REVIEW',
  PRONTO_PARA_DECISAO: 'UNDER_REVIEW',
  APROVADO: 'VALIDATED',
  RECUSADO: 'REJECTED',
  RECEITA_EMITIDA: 'DELIVERED',
  INELEGIVEL: 'REJECTED'
};

const OFFICIAL_TO_LEGACY_STATUS = {
  TRIAGED: 'TRIAGEM',
  QUEUE: 'FILA',
  UNDER_REVIEW: 'EM_ATENDIMENTO',
  MEMED_PROCESSING: 'EM_ATENDIMENTO',
  AWAITING_VALIDATION: 'PRONTO_PARA_DECISAO',
  VALIDATED: 'APROVADO',
  DELIVERED: 'RECEITA_EMITIDA',
  REJECTED: 'RECUSADO',
  FINISHED: 'RECEITA_EMITIDA'
};

function toOfficialStatus(status) {
  return LEGACY_TO_OFFICIAL_STATUS[status] || status;
}

function toLegacyStatus(status) {
  return OFFICIAL_TO_LEGACY_STATUS[status] || status;
}

module.exports = {
  LEGACY_TO_OFFICIAL_STATUS,
  OFFICIAL_TO_LEGACY_STATUS,
  toLegacyStatus,
  toOfficialStatus
};
