/** Nomes oficiais das tabelas — Doctor Prescreve produção */
module.exports = {
  PATIENTS: 'patients',
  PATIENT_ADDRESSES: 'patient_addresses',
  PATIENT_DOCUMENTS: 'patient_documents',
  TRIAGE_SESSIONS: 'triage_sessions',
  TRIAGE_ANSWERS: 'triage_answers',
  MEDICAL_PROTOCOLS: 'medical_protocols',
  MEDICAL_ELIGIBILITY: 'medical_eligibility',
  APPOINTMENTS: 'appointments',
  APPOINTMENT_STATUS_HISTORY: 'appointment_status_history',
  SUPPORT_TICKETS: 'support_tickets',
  SUPPORT_MESSAGES: 'support_messages',
  PAYMENTS: 'payments',
  PAYMENT_EVENTS: 'payment_events',
  PRESCRIPTIONS: 'prescriptions',
  PRESCRIPTION_ITEMS: 'prescription_items',
  PRESCRIPTION_DELIVERY: 'prescription_delivery',
  MEDICAL_RECORDS: 'medical_records',
  MEDICAL_RECORD_VERSIONS: 'medical_record_versions',
  MEDICAL_DECISIONS: 'medical_decisions',
  MEDICAL_LOGS: 'medical_logs',
  AUDIT_LOGS: 'audit_logs',
  INTEGRATION_LOGS: 'integration_logs',
  WHATSAPP_MESSAGES: 'whatsapp_messages',
  WHATSAPP_SESSIONS: 'whatsapp_sessions',
  N8N_EVENTS: 'n8n_events',
  TYPEBOT_SESSIONS: 'typebot_sessions',
  UPLOADED_FILES: 'uploaded_files',
  UPLOADED_PRESCRIPTIONS: 'uploaded_prescriptions',
  DOCTOR_PROFILES: 'doctor_profiles',
  DOCTOR_SESSIONS: 'doctor_sessions',
  DOCTOR_PERMISSIONS: 'doctor_permissions',
  SYSTEM_SETTINGS: 'system_settings',
  SYSTEM_EVENTS: 'system_events',
  ERROR_LOGS: 'error_logs'
};
